### ISSUE TITLE
Asked for a description of a parameter in a void method.

### ISSUE THREAD

**Issue by mitchellslavens** [dbramucci/java-auto-commenter#3]
``` java
 public void displayResults (Student stu){
        System.out.print(stu.toString());
            System.out.print("\n\tPress Enter to display the next student...\n ");
            s.nextLine();
    }
```

This is the method that caused the bug. I was using this on Project 8 when I came across it.

**Comment by dbramucci** [comment]
The code should ask for parameters if the method. It should ask for the description of this method and for the variable stu. It _should not_ ask for a return value. By the way, if you want, in the experimental branch there is a version that will not make comments for the main method.
